spring.application.name=microservicio-sucursales

spring.datasource.url=jdbc:mysql://perfulandia-bd-perfulandia-bd.g.aivencloud.com:22501/defaultdb
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_fk3HeiHdJIngvn_a9yS
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect